### PR TITLE
Fixing bytea json conversion error (update to hibernate 6, spring 3)

### LINKED ISSUE #664: ERROR: operator does not exist: jsonb = bytea
## Description

Hard to rule out a quirk of my setup as the source of this, but on the off chance this is a wider issue thought it worth flagging that I'm currently receiving `ERROR: operator does not exist: jsonb = bytea` from the Spring container on a fresh clone. I understand this issue was identified and fixed as a part of https://github.com/common-workflow-language/cwlviewer/pull/568 (https://github.com/common-workflow-language/cwlviewer/pull/568#discussion_r1729570271), but for some reason it seems to persist for me.

## Expected Behavior

Able to successfully view any example workflows after executing the steps in [Recommended - Running with Docker](https://github.com/common-workflow-language/cwlviewer?tab=readme-ov-file#recommended---running-with-docker).

## Actual Behavior

Unable to view any example workflows.

## Possible Fix

Behaviour is as expected if reverting the changes in 26843b2feba34ede62b803f9f3556ac736e19870.

Fixes attempted with latest commit:

* Later Postgres image versions
* Reverting all (relevant) package version updates since 26843b2feba34ede62b803f9f3556ac736e19870
* Pruning Docker system

## Steps to Reproduce

1. `git clone git@github.com:common-workflow-language/cwlviewer.git`
2. `cd cwlviewer`
3. Optional (issue persists with or without): Switch from Spring image to local build in [docker-compose.yml](https://github.com/common-workflow-language/cwlviewer/blob/main/docker-compose.yml).
4. `docker compose up`
5. Visit [http://localhost:8080/](http://localhost:8080/)
6. Select 'compile' from 'Don't know what to view?'
7. Select 'Parse Workflow'

## Context

Originally occurred after syncing a [fork of CWL Viewer](https://github.com/phenoflow/cwlviewer).

## Your Environment

* Version used: `main`
* Environment name and version (e.g. Chrome 39, Java 17): Chrome 131.0.6778.70. Docker 27.1.1. Arch (256.8-1-arch) via WSL2 (5.15.167.4-microsoft-standard-WSL2)

### PR DESCRIPTION
**Pull request by kinow**
## Description

Closes #664

WIP: will fill in rest later, and move commits to separate pull requests. Just removing warnings while I investigate the issue in #664.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by kinow** [comment]
I think I got all the changes out, and merged. Those were mainly deprecation warnings that I found while trying to run the code, and a missing header. Now wait for GH Actions, then I will perform one final test. Fingers-crossed it will pass, and then it will be ready for someone to review. :crossed_fingers:

**Comment by kinow** [comment]
It worked! To review, one can confirm the code looks alright, GH Actions build is passing, and maybe try `docker compose up` after altering the docker compose file to use the `build: .` so that it builds a new image for the SpringBoot service, instead of using the latest image deployed.

@martinchapman I asked @mr-c to review it, but it would be great if you could try it too, if you have time (or maybe after this gets merged too), to confirm the issue is gone and the viewer is now working for you.

Cheers

**Comment by mr-c** [comment]
Thank you very much @kinow ! Do you know why this wasn't caught by the CI? Do we need a new test?

**Comment by kinow** [comment]
> Thank you very much @kinow ! Do you know why this wasn't caught by the CI? Do we need a new test?

Not a problem, @mr-c :slightly_smiling_face: 

Good point! I think we didn't have a test for retrieving a workflow (or we did, but not necessarily for the part of the code where this happened), only for the queuedworkflow.

I'll write a test once I have time to work on this again. That should give @chapmanb time to take a look too.

Thanks!

File: src/main/java/org/commonwl/view/workflow/WorkflowRepositoryImpl.java [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+            .createNativeQuery(QUERY_FIND_BY_RETRIEVED_FROM, Workflow.class)
+            .unwrap(Query.class);
+
+    if (query == null) {
+      return null;
+    }
+
+    query.setParameter("retrievedFrom", retrievedFrom, new JsonType(GitDetails.class));
+    return (Workflow) query.uniqueResult();
+  }
```
Comment (kinow) [inline src/main/java/org/commonwl/view/workflow/WorkflowRepositoryImpl.java:50]: Note to self: write a test for this!

**Comment by kinow** [comment]
Fixed last warning (it was complaining about our old version of postgres -- 9, while the latest is 17), and added a unit test.

Note, there was one test consistently failing for me, due to a timeout to retrieve spdx licenses. I wonder whether it's a IP block, or maybe only GH Action/AWS/etc are allowed. But if that test fails, it can be ignored as it's not caused by any of the recent changes (you can try `curl -XGET https://....` to fetch the same URL and you should get a connection timed out error as well).

File: src/main/java/org/commonwl/view/workflow/WorkflowRepositoryCustom.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
+/*
+ * Licensed to the Apache Software Foundation (ASF) under one
+ * or more contributor license agreements.  See the NOTICE file
+ * distributed with this work for additional information
+ * regarding copyright ownership.  The ASF licenses this file
+ * to you under the Apache License, Version 2.0 (the
+ * "License"); you may not use this file except in compliance
+ * with the License.  You may obtain a copy of the License at
```
Comment (mr-c) [inline src/main/java/org/commonwl/view/workflow/WorkflowRepositoryCustom.java:8]: cwlviewer is not part of Apache, so perhaps we shouldn't say this?

Comment (kinow) [reply src/main/java/org/commonwl/view/workflow/WorkflowRepositoryCustom.java:8]: +1. Huh, I think I copied the header from another file in the project. I hope I didn't accidentally copy-paste from a file outside the project (or a file that was copied from an AL project).

**Review by mr-c — APPROVED** [review]

**Comment by mr-c** [comment]
Thank you @kinow !
