### PR TITLE
error improvements

### LINKED ISSUE #582: Need better error message when a CommandLineTool is submitted
## Description

CWL Viewer cannot find a workflow in gitlab (self-hosted) repository. 
## Expected Behavior

CWL Viewer shall find and parse the workflow correctly
## Actual Behavior

Error: The workflow could not be found within the repository
## Possible Fix

Must be related to #424
## Steps to Reproduce

1. Go to the https://view.commonwl.org/ and paste the address of the repository https://gitlab.cta-observatory.org/cta-computing/dpps/dpps-workflows.git as URL to workflow. 
2. Paste this commit hash: 76f7c25c0472da23b7e0bfe9f2c18ab6bc369c9d to the "Branch Name/Commit ID" field 
3. Now, the workflow that has been previously registered (long time ago) works: /workflows/calibpipe/uc-cp-001.cwl
4. However, the other workflow (that has not been registered before) doesn't: /workflows/datapipe/uc-dp-XXX.cwl

## Context

I can't render my workflows
## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, Java 17):

### PR DESCRIPTION
**Pull request by mr-c**
- address some deprecations
- detect non-Workflow CWL documents and give a better error message

## Description
When the use provides a path to a CWL document that is not `class: Workflow` or a `$graph` containing a `class: Workflow`, we need a better error message than `Error: The workflow could not be found within the repository`

## Motivation and Context
Fixes #582 

## How Has This Been Tested?
I tested locally with the provided Git repository URL, branch, and path in the original issue.

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by kinow — APPROVED** [review]

**Comment by kinow** [comment]
> @kinow Could you add a test? I'm not familiar with the testing framework

Sorry, saw this comment before approving. Let me take a look…

File: src/main/java/org/commonwl/view/cwl/CWLService.java [hunk 1]
```diff
@@ -204,9 +206,11 @@ public Workflow parseWorkflowNative(
       }
       if (!found && !packedWorkflowId.isEmpty()) throw new WorkflowNotFoundException();
     }
-    if (!found && extractProcess(cwlFile) == CWLProcess.WORKFLOW) {
-      // Check the current json node is a workflow
+    if (!found && (extractProcess(cwlFile) == CWLProcess.WORKFLOW)) {
       found = true;
+    } else if (found && (extractProcess(cwlFile) != CWLProcess.WORKFLOW)) {
```
Comment (kinow) [inline src/main/java/org/commonwl/view/cwl/CWLService.java:211]: Interesting, @mr-c. I tried writing a unit test for this, but I couldn't make the service to reach this line. The `found` starts as `false`. And unless it's set before, it will not enter this `else if` block.

To make it eval to `true`, I packed the CommandLineTool,

```cwl
cwlVersion: v1.2
$graph:
- id: echo
  class: CommandLineTool
  baseCommand: echo
  inputs: []
  outputs: []
```

but that still results in `false` since the code above already checks if it is a packed workflow, and only sets `found` to `true` in that case.

Did you reach this part of the code testing with the application running?

File: src/main/java/org/commonwl/view/workflow/WorkflowService.java [hunk 2]
```diff
@@ -338,7 +339,7 @@ public QueuedWorkflow createQueuedWorkflow(GitDetails gitInfo)
 
       // Check workflow is readable
       if (!Files.isReadable(workflowFile)) {
-        throw new WorkflowNotFoundException();
+        throw new WorkflowNotFoundException("Unable to read workflow file on disk.");
```
Comment (kinow) [inline src/main/java/org/commonwl/view/workflow/WorkflowService.java:342]: :+1:

File: src/main/java/org/commonwl/view/cwl/CWLService.java (hunk 1 above)
Comment (kinow) [reply src/main/java/org/commonwl/view/cwl/CWLService.java:211]: I tried with

```cwl
cwlVersion: v1.2

# What type of CWL process we have in this document.
class: CommandLineTool

label: Process DL0 to DL3

doc: >
    This tool (must become a workflow) 
    processes DL0 to DL3 simulated data.

baseCommand: echo

inputs:
    metadata_queue:
        type: File
        inputBinding: 
            prefix: --metadata-queue
            position: 1
    
outputs:
    dl3:
        type: File[]
        outputBinding:
            glob: '*.txt'
    dl3_metadata:
        type: stdout
    irfs:
        type: File[]
        outputBinding:
            glob: '*.txt'
    irfs_metadata:
        type: stdout

stdout: output.txt
```

And it still couldn't reach that part of the code. Here's the test:

```diff
diff --git a/src/test/java/org/commonwl/view/cwl/CWLServiceTest.java b/src/test/java/org/commonwl/view/cwl/CWLServiceTest.java
index 384fcd4..fe6993d 100644
--- a/src/test/java/org/commonwl/view/cwl/CWLServiceTest.java
+++ b/src/test/java/org/commonwl/view/cwl/CWLServiceTest.java
@@ -442,4 +442,24 @@ public class CWLServiceTest {
       assertEquals(CWLProcess.COMMANDLINETOOL, steps.get("lobSTR").getRunType());
     }
   }
+
+  @Test
+  public void testExceptionRaisedForCommandLineTool() {
+    Exception thrown =
+            Assertions.assertThrows(
+                    CWLNotAWorkflowException.class,
+                    () -> {
+                      CWLService cwlService =
+                              new CWLService(
+                                      Mockito.mock(RDFService.class),
+                                      Mockito.mock(CWLTool.class),
+                                      Mockito.mock(GitConfig.class).licenseVocab(),
+                                      999999);
+                      cwlService.parseWorkflowNative(
+                              Paths.get("src/test/resources/cwl/invalid_is_a_packed_command_line.cwl"), "");
+                    });
+    assertEquals(
+            "File 'lobSTR-workflow.cwl' is over singleFileSizeLimit - 2 KB/0 bytes",
+            thrown.getMessage());
+  }
 }
```

Just create the CWL file at `src/test/resources/cwl/invalid_is_a_packed_command_line.cwl`

Comment (kinow) [reply src/main/java/org/commonwl/view/cwl/CWLService.java:211]: (WIP test, I copied another test and was modifying it, slowly altering and re-running it)

**Comment by kinow** [comment]
(Clicked on Update branch -- forgot to check if there was an option to rebase...)

**Comment by mr-c** [comment]
@kinow I rebased and fixed the conflicts
